// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrmixsvdnejzfxvybmng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpybWl4c3ZkbmVqemZ4dnlibW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4MTk0NjAsImV4cCI6MjA5MjM5NTQ2MH0.pyIGuacTkWI7UQID2Dc7wh2jrGPBaYBDMhGw4E1d_ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});